const jwt = require('jsonwebtoken');
const User = require('../models/User');
const config = require('../config');
const { isSiteOnline } = require('../controllers/siteController');

/**
 * Protect routes — verify JWT token and attach user to req.
 */
const protect = async (req, res, next) => {
  try {
    const gatewaySecret = req.headers['x-gateway-secret'];
    const expectedSecret = process.env.GATEWAY_SECRET || "super_secret_gateway_key_2026";

    let user;

    // 1. Check if the request comes from the API Gateway
    if (gatewaySecret === expectedSecret) {
      const authUserStr = req.headers['x-auth-user'];
      if (!authUserStr) {
        return res.status(401).json({ success: false, message: 'Gateway provided no user data' });
      }

      const supabaseUser = JSON.parse(authUserStr);
      
      // Auto-provision or fetch MongoDB user based on email
      user = await User.findOne({ email: supabaseUser.email });
      
      if (!user) {
        // Create MongoDB user on the fly
        user = await User.create({
          name: supabaseUser.name || supabaseUser.username,
          email: supabaseUser.email,
          password: 'AutoGeneratedPassword123!', 
          role: supabaseUser.role || 'student',
          isActive: supabaseUser.is_active !== false,
          rollNumber: `ROLL_${Math.floor(Math.random()*10000)}`,
          mobileNumber: '0000000000',
          collegeName: 'SyncLearn',
          branch: 'General'
        });
      } else {
        // Sync role and active status
        let updated = false;
        if (user.role !== supabaseUser.role) { user.role = supabaseUser.role; updated = true; }
        if (user.isActive !== (supabaseUser.is_active !== false)) { user.isActive = supabaseUser.is_active !== false; updated = true; }
        if (updated) await user.save();
      }
    } else {
      // 2. Fallback to standard JWT (for direct MCQ backend access)
      let token;
      if (req.headers.authorization && req.headers.authorization.startsWith('Bearer')) {
        token = req.headers.authorization.split(' ')[1];
      }

      if (!token) {
        return res.status(401).json({ success: false, message: 'Not authorized — no token provided' });
      }

      const decoded = jwt.verify(token, config.jwt.secret);
      user = await User.findById(decoded.id);
      if (!user) {
        return res.status(401).json({ success: false, message: 'User belonging to this token no longer exists' });
      }
    }

    if (!user.isActive) {
      return res.status(403).json({ success: false, message: 'Your account has been deactivated. Contact admin.' });
    }

    if (user.role !== 'admin' && !(await isSiteOnline())) {
      return res.status(503).json({ success: false, message: 'The website is currently offline. Please try again later.', code: 'SITE_OFFLINE' });
    }

    req.user = user;
    next();
  } catch (error) {
    console.error('Auth Middleware Error:', error);
    return res.status(401).json({ success: false, message: 'Not authorized — token invalid or expired' });
  }
};

/**
 * Restrict access to specific roles.
 * Usage: authorize('admin', 'teacher')
 */
const authorize = (...roles) => {
  return (req, res, next) => {
    if (!roles.includes(req.user.role)) {
      return res.status(403).json({
        success: false,
        message: `Role '${req.user.role}' is not authorized to access this resource`,
      });
    }
    next();
  };
};

module.exports = { protect, authorize };
