services:
  - type: web
    name: synclearn-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CLIENT_URL
        sync: false
      - key: UPLOAD_DIR
        value: uploads
      - key: MAX_FILE_SIZE
        value: 5242880
      - key: ADMIN_NAME
        value: System Admin
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_USERNAME
        value: synclearn_admin
      - key: GATEWAY_SECRET
        sync: false
